export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';

export const SET_ERRORS = 'SET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';

export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
